export const GET_ALL_CANDIDATES_REQUEST = 'GET_ALL_CANDIDATES_REQUEST';
export const GET_ALL_CANDIDATES_SUCCESS = 'GET_ALL_CANDIDATES_SUCCESS';
export const GET_ALL_CANIDDATES_FAILURE = 'GET_ALL_CANDIDATES_FAILURE';
export const MOVE_CANDIDATES = 'MOVE_CANDIDATES';
