export const GET_ALL_CANDIDATES_REQUEST = 'GET_ALL_CANDIDATES_REQUEST';
export const GET_ALL_CANDIDATES_SUCCESS = 'GET_ALL_CANDIDATES_SUCCESS';
export const GET_ALL_CANIDDATES_FAILURE = 'GET_ALL_CANDIDATES_FAILURE';
export const UPDATE_CANDIDATE_STATUS_REQUEST = 'UPDATE_CANDIDATE_STATUS_REQUEST';
export const UPDATE_CANDIDATE_STATUS_SUCCESS = 'UPDATE_CANDIDATE_STATUS_SUCCESS';
export const UPDATE_CANDIDATE_STATUS_FAILURE = 'UPDATE_CANDIDATE_STATUS_FAILURE';
